on:
  push: {}
  workflow_dispatch: {}

jobs:
  interp:
    runs-on: ubuntu-latest

    env:
      V1: VALUE1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Populate environment via GITHUB_ENV
        run: |
          echo "Z1=VALUE1" >> $GITHUB_ENV
      
      - name: XXX
        shell: bash
        env:
          Z2: VALUE2
        run: |
          echo "$V1"
          echo "$Z1"
          echo "$Z2"